---
layout: cv
title: Keith Crawford's Resume
---
# Keith Crawford
Aspiring Computer Science Student

<div id="webaddress">
<a href="cra22033@byui.edu">cra22033@byui.edu</a>
| <a href="https://github.com/crawfordk99">My Github Account</a>
  <a href="https://www.linkedin.com/in/kcjr3">My LinkedIn</a>
</div>

<!-- https://www.monique.tech/the-art-of-markdown -->


## Education

`Expected 2026`
__Brigham Young University-Idaho__, Rexburg, ID

- BS in Computer Science 
- 4.0 GPA

`2013-2017`
__Warren Township High School__, Gurnee, IL

- High School Degree


## Experience

### Survey Interviewer

`February 2023 - Present`
__Ironwood Insights Group__, Interviewer

- Conducted unbiased surveys ranging from 2-25 minutes
- Entered responses to computer verbatim

## Service and Work History

`August 2023 - December 2023`
__360 Logistics LLC__, Delivery Driver

- Delivered 250-300 packages daily

`2020-2022`
__Service Missionary__, Tucson Arizona & Vancouver Canada

- Updated database daily with reports on interactions with people in the area

## Skills

- Python (experience with plotly express, pandas, scikit-learn)
- Cuarto
- HTML
- CSS
- C#
- MySQL